### PR TITLE
Added to Citing Fellows and Other Academics

### PR DESCRIPTION
**Pull request by kchatlosh**
feel free to edit/revise

### CODE REVIEW

**Review by kallewesterling — APPROVED** [review]
Looks good to me. @lmrhody and @smythp you may want to take a look at these edits as well.

**Comment by smythp** [comment]
> ...are essentially the work just one Fellow...

work of just one

> of attributing of each other

of attributing each other

I appreciate the shout-out in this, but really don't feel like I need any additional attribution in any of these. In general I think this is too long and complicated and we should try to boil it down to three sentences or so if remotely possible, just because this is too much to expect from people. I actually just think they should say it was the work of GCDI and have to link back to the repository, with perhaps a note mentioning individual contributors as a nice gesture. That's pretty much what people usually do with CC, and honestly I'm not sure attribution on these is going to make or break our careers. That's my feeling, anyway, and might be colored by being a coder where the norms around this stuff are pretty different.

**Comment by kallewesterling** [comment]
Yeah, I was also thinking that this is also the purpose of having all of this here on GitHub, as you can track back through the changes/commits/pull requests and see who has contributed in the history of each of the files, right?

**Comment by smythp** [comment]
Yes, it's all there :)

**Comment by kchatlosh** [comment]
Hi all,

Wait so we're not including the section on "## Citing Fellows and Other Academics" in the Style Guide or elsewhere on the DHRI Curriculum? I'm getting a bit confused in the history section on GitHub and the messages here, so maybe I'm not following this correctly. 

As I wrote to Kalle earlier, and added @lmrhody --
When this DHRI curriculum gets published into a GitBook that then gets shared around and read by people on and off GitHub, I think it's really important that it is clear who did what work (without having to go trace it on GitHub) and the work of individuals doesn't get subsumed under the name of the organization. This will affect not just what individuals can list on their CVs, but also how this curriculum gets cited and who gets credited. This section is meant to explain a bit about our citational practices and the meaning behind the two main forms of attribution that are included across the various DHRI workshops.

**Comment by kallewesterling** [comment]
Adding this conversation to our next meeting agenda, @lmrhody!

**Pull request closed without merging**
